### ISSUE TITLE
文档照搬写错了

### ISSUE THREAD

**Issue by jiqing112** [shuosc/mirrorhelp#3]
[Fedora 源使用帮助](https://mirrors.shu.edu.cn/help/fedora.html
)

[![PdOSrq.md.png](https://s1.ax1x.com/2018/07/31/PdOSrq.md.png)](https://imgchr.com/i/PdOSrq)

**Comment by zhonger** [comment]
@jiqing112 哈哈，感谢提醒。我发现里面的命名没有改过来，`fedora-ustc.repo`这样的`ustc`，应改为`shu`。现已修改，不知道还有吗？

**Comment by jiqing112** [comment]
不知道，应该没了，我只用Fedora

**Comment by zhonger** [comment]
好的，感谢关注。
